# Generated by Django 3.2.3 on 2021-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=120)),
                ('reason', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('occupation', models.CharField(max_length=120)),
                ('DOB', models.DateField()),
                ('date', models.DateField()),
            ],
        ),
    ]
