# Generated by Django 3.2.3 on 2021-05-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_joinus'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='gender',
            field=models.CharField(default='not specified', max_length=20),
        ),
    ]
