# Generated by Django 3.2.3 on 2021-05-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_joinus_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinus',
            old_name='date',
            new_name='Request_date',
        ),
    ]
